#!/usr/bin/env python3
"""Apply exact-version, source-bound dependency license evidence.

This post-processes the offline supply-chain artifacts generated by
``build_supply_chain_evidence.py``. Evidence only applies when ecosystem,
name, declared spec, and manifest all match exactly. A stale or unmatched
record remains a blocker and can never silently clear a newer dependency.
License evidence cannot clear the independent resolved-transitive-SBOM gate.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_VERIFICATION_DIR = ROOT / "verification"
DEFAULT_EVIDENCE_FILE = ROOT / "multimodal" / "dependency-license-evidence.json"
SHA40 = re.compile(r"^[0-9a-f]{40}$")
TRANSITIVE_SBOM_BLOCKER = "resolved transitive SBOM has not been generated or verified"


def load_json(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"Cannot read valid JSON from {path}: {exc}") from exc
    if not isinstance(payload, dict):
        raise ValueError(f"Expected a JSON object in {path}")
    return payload


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def evidence_key(ecosystem: str, name: str, declared_spec: str, manifest: str) -> tuple[str, str, str, str]:
    return ecosystem.casefold(), name.casefold(), declared_spec, manifest


def validate_record(record: Any, index: int) -> tuple[tuple[str, str, str, str], dict[str, Any]]:
    if not isinstance(record, dict):
        raise ValueError(f"License evidence record {index} must be an object")
    required = ("ecosystem", "name", "version", "declaredSpec", "manifest", "license", "status", "source")
    for field in required:
        if field not in record:
            raise ValueError(f"License evidence record {index} is missing {field}")
    for field in ("ecosystem", "name", "version", "declaredSpec", "manifest", "license", "status"):
        if not isinstance(record[field], str) or not record[field].strip():
            raise ValueError(f"License evidence record {index} has invalid {field}")
    if record["status"] != "source-verified":
        raise ValueError(f"License evidence record {index} is not source-verified")
    if record.get("legalApproval") is not False:
        raise ValueError(f"License evidence record {index} must keep legalApproval false")
    source = record["source"]
    if not isinstance(source, dict):
        raise ValueError(f"License evidence record {index} source must be an object")
    for field in ("repository", "tag", "path", "blobSha"):
        if not isinstance(source.get(field), str) or not source[field].strip():
            raise ValueError(f"License evidence record {index} has invalid source.{field}")
    if source["tag"] != record["version"]:
        raise ValueError(f"License evidence record {index} source tag must equal the exact version")
    if not SHA40.fullmatch(source["blobSha"]):
        raise ValueError(f"License evidence record {index} source blobSha must be a lowercase 40-character SHA")
    if record["ecosystem"].casefold() == "pypi":
        expected = f"{record['name']}=={record['version']}"
        if record["declaredSpec"] != expected:
            raise ValueError(f"License evidence record {index} declaredSpec must be {expected}")
    key = evidence_key(record["ecosystem"], record["name"], record["declaredSpec"], record["manifest"])
    return key, record


def component_properties(component: dict[str, Any]) -> dict[str, str]:
    result: dict[str, str] = {}
    properties = component.get("properties", [])
    if isinstance(properties, list):
        for item in properties:
            if isinstance(item, dict) and isinstance(item.get("name"), str) and isinstance(item.get("value"), str):
                result[item["name"]] = item["value"]
    return result


def apply_evidence(verification_dir: Path, evidence_file: Path) -> dict[str, Any]:
    inventory_path = verification_dir / "license-inventory.json"
    supply_path = verification_dir / "supply-chain-evidence.json"
    sbom_path = verification_dir / "source-sbom.cdx.json"
    inventory = load_json(inventory_path)
    supply = load_json(supply_path)
    sbom = load_json(sbom_path)
    evidence = load_json(evidence_file)

    if evidence.get("schemaVersion") != "1.0.0":
        raise ValueError("dependency license evidence schemaVersion must be 1.0.0")
    records = evidence.get("records")
    if not isinstance(records, list):
        raise ValueError("dependency license evidence records must be an array")

    indexed: dict[tuple[str, str, str, str], dict[str, Any]] = {}
    for index, raw_record in enumerate(records):
        key, record = validate_record(raw_record, index)
        if key in indexed:
            raise ValueError(f"Duplicate dependency license evidence key: {key}")
        indexed[key] = record

    components = inventory.get("components")
    if not isinstance(components, list):
        raise ValueError("license inventory components must be an array")

    matched_keys: set[tuple[str, str, str, str]] = set()
    applied: list[dict[str, Any]] = []
    for row in components:
        if not isinstance(row, dict) or row.get("licenseKnown") is True:
            continue
        key = evidence_key(
            str(row.get("ecosystem", "")),
            str(row.get("name", "")),
            str(row.get("declaredSpec", "")),
            str(row.get("manifest", "")),
        )
        record = indexed.get(key)
        if record is None:
            continue
        source = record["source"]
        row["license"] = record["license"]
        row["licenseKnown"] = True
        row["licenseEvidence"] = {
            "status": record["status"],
            "legalApproval": False,
            "repository": source["repository"],
            "tag": source["tag"],
            "path": source["path"],
            "blobSha": source["blobSha"],
        }
        matched_keys.add(key)
        applied.append({
            "ecosystem": record["ecosystem"],
            "name": record["name"],
            "version": record["version"],
            "manifest": record["manifest"],
            "license": record["license"],
            "sourceBlobSha": source["blobSha"],
        })

    unknown_required = sorted(
        f"{row.get('ecosystem')}:{row.get('name')}@{row.get('declaredSpec')} ({row.get('manifest')})"
        for row in components
        if isinstance(row, dict) and row.get("scope") != "development" and row.get("licenseKnown") is not True
    )
    unmatched = sorted(
        f"{record['ecosystem']}:{record['name']}@{record['declaredSpec']} ({record['manifest']})"
        for key, record in indexed.items()
        if key not in matched_keys
    )

    inventory["unknownRequiredLicenses"] = unknown_required
    inventory["coverageComplete"] = not unknown_required and not unmatched
    inventory["appliedLicenseEvidence"] = sorted(applied, key=lambda item: (item["ecosystem"], item["name"], item["version"]))
    inventory["unmatchedLicenseEvidence"] = unmatched
    inventory["claimBoundary"] = (
        "License identification is complete only when every non-development dependency has an exact, source-bound license. "
        "This evidence is not legal approval, promotion clearance, or proof of a resolved transitive SBOM."
    )

    sbom_components = sbom.get("components")
    if not isinstance(sbom_components, list):
        raise ValueError("SBOM components must be an array")
    for component in sbom_components:
        if not isinstance(component, dict):
            continue
        props = component_properties(component)
        purl = str(component.get("purl", ""))
        ecosystem = "pypi" if purl.startswith("pkg:pypi/") else ("npm" if purl.startswith("pkg:npm/") else "")
        key = evidence_key(ecosystem, str(component.get("name", "")), props.get("urai:declaredSpec", ""), props.get("urai:manifest", ""))
        record = indexed.get(key)
        if record is None or key not in matched_keys:
            continue
        component["licenses"] = [{"license": {"name": record["license"]}}]
        source = record["source"]
        properties = component.setdefault("properties", [])
        properties.append({"name": "urai:licenseEvidenceRepository", "value": source["repository"]})
        properties.append({"name": "urai:licenseEvidenceTag", "value": source["tag"]})
        properties.append({"name": "urai:licenseEvidenceBlobSha", "value": source["blobSha"]})
        properties.append({"name": "urai:legalApproval", "value": "false"})

    blockers = [
        str(item)
        for item in supply.get("blockers", [])
        if not str(item).startswith("unknown required license:")
        and not str(item).startswith("unmatched license evidence:")
    ]
    blockers.extend(f"unknown required license: {item}" for item in unknown_required)
    blockers.extend(f"unmatched license evidence: {item}" for item in unmatched)

    resolved_transitive_complete = supply.get("resolvedTransitiveSbomComplete") is True
    if not resolved_transitive_complete:
        blockers.append(TRANSITIVE_SBOM_BLOCKER)
    blockers = sorted(set(blockers))

    supply["unknownRequiredLicenses"] = unknown_required
    supply["unmatchedLicenseEvidence"] = unmatched
    supply["appliedLicenseEvidenceCount"] = len(applied)
    supply["licenseEvidenceFile"] = evidence_file.relative_to(ROOT).as_posix() if evidence_file.is_relative_to(ROOT) else str(evidence_file)
    supply["licenseCoverageComplete"] = not unknown_required and not unmatched
    supply["resolvedTransitiveSbomComplete"] = resolved_transitive_complete
    supply["sbomComplete"] = resolved_transitive_complete and supply.get("sbomComplete") is True
    supply["releaseEligible"] = not blockers and supply["sbomComplete"] is True
    supply["blockers"] = blockers
    supply["claimBoundary"] = (
        "Exact-version license identification can clear only license blockers. Release remains blocked until a separately generated "
        "and verified resolved transitive SBOM and every independent release gate are complete."
    )

    write_json(inventory_path, inventory)
    write_json(sbom_path, sbom)
    write_json(supply_path, supply)
    return supply


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--verification-dir", type=Path, default=DEFAULT_VERIFICATION_DIR)
    parser.add_argument("--evidence-file", type=Path, default=DEFAULT_EVIDENCE_FILE)
    parser.add_argument("--require-complete", action="store_true")
    args = parser.parse_args()
    try:
        result = apply_evidence(args.verification_dir.resolve(), args.evidence_file.resolve())
    except ValueError as exc:
        print(json.dumps({"status": "invalid-license-evidence", "error": str(exc)}, indent=2))
        return 2
    print(json.dumps(result, indent=2, sort_keys=True))
    if args.require_complete and (
        result.get("licenseCoverageComplete") is not True
        or result.get("resolvedTransitiveSbomComplete") is not True
        or result.get("releaseEligible") is not True
    ):
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
