#!/usr/bin/env python3
from __future__ import annotations
import csv,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'xr-test-packet'
CASES=[
('XR-001','launch','Install and launch build','App reaches home world without crash','ready_for_execution'),
('XR-002','performance','Home world 10 minute traversal','Median >=72 fps and p95 frame time <=18 ms','ready_for_execution'),
('XR-003','controls','Controller select, grab, back and menu','All mapped actions respond within 150 ms','ready_for_execution'),
('XR-004','hands','Enable hand tracking and repeat primary actions','Supported gestures recognized without unsafe fallback','ready_for_execution'),
('XR-005','comfort','Turn, locomote, stop and recenter','No forced camera acceleration; recenter completes','ready_for_execution'),
('XR-006','boundary','Approach and cross guardian boundary','Runtime yields safely to system boundary','ready_for_execution'),
('XR-007','focus','Remove headset, resume and recover focus','Audio and simulation pause/resume without duplication','ready_for_execution'),
('XR-008','audio','Route audio, mute, unmute and device change','No clipping; controls persist and essential meaning remains','ready_for_execution'),
('XR-009','thermal','Sustained 30 minute session','No crash, runaway memory or severe thermal degradation','ready_for_execution'),
('XR-010','recovery','Suspend, network loss and relaunch','State recovers or fails with clear safe messaging','ready_for_execution')]
def main():
 OUT.mkdir(parents=True,exist_ok=True)
 with (OUT/'test-cases.csv').open('w',newline='') as f:
  w=csv.writer(f); w.writerow(['test_id','area','procedure','expected_result','status']); w.writerows(CASES)
 schema={'$schema':'https://json-schema.org/draft/2020-12/schema','title':'URAI Quest Device Receipt','type':'object','required':['buildSha','deviceModel','osVersion','testId','startedAtUtc','completedAtUtc','status','evidence'],'properties':{'buildSha':{'type':'string','pattern':'^[0-9a-f]{40}$'},'deviceModel':{'type':'string','minLength':1},'osVersion':{'type':'string','minLength':1},'testId':{'type':'string','pattern':'^XR-[0-9]{3}$'},'startedAtUtc':{'type':'string','format':'date-time'},'completedAtUtc':{'type':'string','format':'date-time'},'status':{'enum':['passed','failed','blocked']},'fpsMedian':{'type':['number','null']},'frameTimeP95Ms':{'type':['number','null']},'evidence':{'type':'array','items':{'type':'string'}},'notes':{'type':'string'}}}
 (OUT/'device-receipt-schema.json').write_text(json.dumps(schema,indent=2)+'\n')
 template={'schemaVersion':'1.0.0','namingPattern':'XR-[BUILD]-[DEVICE]-[TEST-ID]-[UTC-TIMESTAMP]-[EVIDENCE-TYPE].[ext]','receipts':[]}
 (OUT/'evidence-manifest-template.json').write_text(json.dumps(template,indent=2)+'\n')
 (OUT/'test-plan.md').write_text('# Physical Quest test plan\n\nStatus: **ready for execution; not physically verified**.\n\nPrerequisites: exact build SHA, Quest developer mode, charged device, controller batteries, USB/ADB access, clean guardian, stable Wi-Fi, screen recording, and performance overlay. Capture model, OS, runtime version, battery and thermal state. Execute every row in `test-cases.csv`; retain screenshots/video/logcat/performance captures using the required filename pattern.\n\nThresholds: target 72 fps minimum unless product configuration requires higher; median >=72 fps, p95 frame time <=18 ms, input response <=150 ms, no repeated dropped-audio events, no essential information conveyed only by motion or sound. Human comfort assessment is required.\n')
 (OUT/'execution-log-template.md').write_text('# XR execution log\n\n- Build SHA:\n- Device model:\n- OS/runtime version:\n- Tester:\n- UTC start/end:\n\n| Test ID | Status | Evidence files | Metrics | Notes |\n|---|---|---|---|---|\n')
 (OUT/'defect-template.md').write_text('# XR defect\n\n- Severity: blocker / critical / major / minor\n- Build SHA:\n- Device/OS:\n- Test ID:\n- Steps:\n- Expected:\n- Actual:\n- Reproduction rate:\n- Evidence:\n- Retest result:\n')
 (OUT/'README.md').write_text('# XR test packet\n\nGenerated by `python scripts/build_xr_test_packet.py`. Validate JSON with `python -m json.tool` and CSV with Python `csv`. Physical execution on the target Quest device remains mandatory.\n')
 print(json.dumps({'testCases':len(CASES),'status':'completed_unverified_external'},indent=2))
if __name__=='__main__': main()
